feat: Updated CSPROJ version. #179944
audaciaconsulting/Audacia.Log pull request #8
Opened 2024-10-23 13:28 UTC by charliebenjamin-audacia

…M, updated changelogs to reflect past changes. #179944

| Action | Done? |
| --- | --- |
| CHANGELOG updated | ✔ |
| Code compiles and unit tests all pass locally | ✔ |
| Debug/console log code removed | ✔ |
| Commented out code removed | ✔ |
| Unit tests added/updated | ✔ |
| README updated | ✔ |
| Considered: <br /> - Performance <br /> - Security <br /> - Logging | ✔ |
| Licenses of any new/upgraded dependencies checked, with no copyleft dependencies introduced | ✔ |

2024-10-25 12:51 UTC, kieran-wilkinson-audacia approved these changes, later dismissed

2024-11-19 12:34 UTC, jackpercy-acl requested changes

2024-11-19 12:34 UTC, jackpercy-acl commented on build.yaml
> +schedules:
Schedule can be removed

2024-11-19 14:19 UTC, richardb355 commented on build.yaml
> +schedules:
Removed

2024-11-19 15:09 UTC, jackpercy-acl submitted a review, later dismissed

2024-11-20 17:14 UTC, jackpercy-acl submitted a review, later dismissed

2024-11-20 17:26 UTC, jackpercy-acl approved these changes

2024-11-20 17:29 UTC, merged